### ISSUE TITLE
odata.nextLink not working

### ISSUE THREAD

**Issue by jraadt** [fhellwig/graph-service#2]
I had to change line 63 `path = body['@odata.nextLink'] || null;` to `path = body['odata.nextLink'] || null;` or `path` would always be null.  I'm using `graph.windows.net` so maybe that makes a difference.  Great library!  Thanks!

**Comment by fhellwig** [comment]
I change line 63 to `path = body['@odata.nextLink'] || body['odata.nextLink'] || null;` so that should cover both cases.
