### ISSUE TITLE
using POST to create new user

### ISSUE THREAD

**Issue by gciluffo** [fhellwig/graph-service#4]
The library seems to hang when I try to create a new user. Im simply doing
```
graph.post('/v1.0/users', req.body, (err: any, response: any) => {
        if (!err) {
          res.json(response);
          return next();
        }
});
```

Where req.body is 
```
{
  "accountEnabled": true,
  "displayName": "Alex Wu",
  "mailNickname": "AlexW",
  "passwordProfile": {
    "password": "Test1234",
    "forceChangePasswordNextLogin": false
  },
  "userPrincipalName": "Alex@a830edad9050849NDA1.onmicrosoft.com"
}
```

Anyone else having this issue?
Looking at <a href="https://msdn.microsoft.com/library/azure/ad/graph/api/users-operations#CreateUser">this</a> for documentation.

**Comment by fhellwig** [comment]
Please try `forceChangePasswordNextSignIn` instead of `forceChangePasswordNextLogin`.
