### ISSUE TITLE
difference to https://github.com/microsoftgraph/msgraph-sdk-javascript

### ISSUE THREAD

**Issue by stevezau** [fhellwig/graph-service#5]
Hi,

Can i ask what the difference is to https://github.com/microsoftgraph/msgraph-sdk-javascript ?

**Comment by fhellwig** [comment]
I'm sure the Microsoft library is more full-featured and better-tested. If you look at the initial commit dates, mine was four months before Microsoft's so I didn't have this alternative at that time.
